#theme: jekyll-theme-chirpy
# _config.yml
remote_theme: pages-themes/cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme

title: Bless Jah
description: Project Portfolio

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
